apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-spring-k8s
  template:
    metadata:
      labels:
        app: java-spring-k8s
    spec:
      containers:
        - name: backend
          image: eobilas/java-spring-kubernetes:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080